# https://cert-manager.io/docs/configuration/acme/dns01/digitalocean/
---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  # insert your base64 encoded DigitalOcean access token here
  # DO_PAT64=$(echo $DO_PAT | base64 -w 0)
  # cat digitalocean-dns-secret.yaml | sed "s/{{DO_PAT}}/$DO_PAT64/" | kubectl apply -f -
  access-token: "{{DO_PAT}}"
