# https://github.com/jetstack/cert-manager/issues/1406
---
#apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-do-certificate
  namespace: default
spec:
  secretName: wildcard-do-tls
  issuerRef:
    name: letsencrypt-do-dns-wildcard-prod
    kind: Issuer # not ClusterIssuer in examples
  commonName: '*.do.fabianlee-lab.online'
  dnsNames:
  - '*.do.fabianlee-lab.online'
#  acme:
#    config:
#    - dns01:
#        provider: letsencrypt-do-dns-wildcard-prod
#      domains:
#      - '*.do.fabianlee-lab.online'
