# https://github.com/jetstack/cert-manager/issues/1406
---
#apiVersion: certmanager.k8s.io/v1alpha1
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: do-wildcard-certificate
  namespace: default
spec:
  secretName: secondary-letsencrypt-tls # ingress tls secret name
  issuerRef:
    name: letsencrypt-dns-wildcard-prod
    kind: Issuer # not ClusterIssuer in examples
  #commonName: 'foo.do.fabianlee-lab.online'
  commonName: '*.do.fabianlee-lab.online'
  dnsNames:
  #- foo.do.fabianlee-lab.online
  - '*.do.fabianlee-lab.online'
#  acme:
#    config:
#    - dns01:
#        provider: prod-dns
#      domains:
#      - third.do.fabianlee-lab.online
