# used for manual deployments
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-hello-world-web-service
  #namespace: default
  annotations:
    # https://github.com/ubuntu/microk8s/issues/2035
    # 'nginx' is default for nginx manifests, microk8s changed default to 'public' at microk8s 1.20
    kubernetes.io/ingress.class: nginx

    # allows http without forcing redirect to ssl
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  tls:
  - hosts: [ 'k3s.local' ]
    # secret must be in same namespace
    secretName: tls-credential
  rules:

  - host: k3s.local
    http:
      paths:
      - pathType: Prefix #Exact
        path: "/myhello/"
        backend:
          service:
            name: golang-hello-world-web-service
            port:
              number: 8080

