---

# get latest ansible role for installing microk8s
- hosts: localhost
  become: no
  tasks:

    - name: make collections directory
      file:
        path: "{{playbook_dir}}/../collections"
        state: directory

    # https://galaxy.ansible.com/community/kubernetes
    - name: get community.kubernetes collection from ansible galaxy, be patient can take 5 minutes
      command:
        cmd: ansible-galaxy collection install community.kubernetes:1.2.1 -p .
        creates: "{{playbook_dir}}/../collections/ansible_collections/community/kubernetes"
        chdir: "{{playbook_dir}}/../collections"
