---

- hosts: master
  gather_facts: yes
  become: yes

  # most vars are coming from 'group_vars/' directory
  vars:
    # version needed by more than one role (namespace labels)
    istio_version: 1.9.7 # validated on 1.7.5 and 1.9.7
    istio_ingress_tested_from_localhost: true

  roles:
    # public LB endpoints
    - role: k3s-metallb

    # istio operator (istio-operator) and primary+secondary ingress gateway services (istio-system)
    - role: istio-operator

    # istio gateways (primary and secondary)
    - role: istio-gateway

    # put TLS secret into 'istio-system' namespace also
    - { role: apply-k8s-tls-secrets, secret_namespace_list: [ 'default','istio-system'] }

    # deploys hello world apps, projected unto primary and secondary gateway
    - role: istio-helloworld

  tasks:
  - name: run tests against istio gateways
    include_role:
      name: istio-gateway
      tasks_from: test.yml

