# https://cert-manager.io/docs/configuration/acme/dns01/digitalocean/
---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  # insert your DO access token here
  # echo $DO_PAT | base64 -w 0
  access-token: "***REMOVED***"
