apiVersion: cert-manager.io/v1
kind: Issuer # in examples, is not ClusterIssuer
metadata:
  name: letsencrypt-do-dns-prod
spec:
  acme:
    # Email address used for ACME registration
    email: flee999@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: letsencrypt-do-dns-prod-private-key
    # Add a single challenge solver, DNS01 using digital ocean
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
      selector:
        dnsNames:
        - 'third.do.fabianlee-lab.online'
        #- '*.do.fabianlee-lab.online'
