---
- name: install python3 packages
  apt:
    pkg:
    - software-properties-common
    - python3
    - python3-pip
    - python3-setuptools
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: apt_install
  retries: 3
  delay: 60
  until: apt_install is success or ('Unable to acquire the dpkg frontend lock' not in apt_install.msg)

- name: install required pip3 dependencies for ansible galaxy kubernetes modules
  become: yes
  pip:
    name:
      - requests
      - pyyaml
    executable: pip3
    # not necessary to use extra_args
    #extra_args: --upgrade pip

- name: Add an apt key by id from a keyserver
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367

- name: add ansible ppa repository
  apt_repository:
    repo: 'ppa:ansible/ansible'
    state: present
    validate_certs: false
    update_cache: true

- name: install ansible-base package
  apt:
    pkg:
    - ansible-core
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  register: apt_install
  retries: 3
  delay: 60
  until: apt_install is success or ('Unable to acquire the dpkg frontend lock' not in apt_install.msg)

- command:
    cmd: ansible --version
  register: ansible_ver
- debug: msg="{{ansible_ver.stdout_lines}}"

